@startuml create_team
actor client
control controller
participant "team.action" as team_action
database team
autonumber

client -> controller: post /v1/team
activate controller

    controller -> team_action: createTeam()
    activate team_action
        team_action -> team: insert()
        activate team
        return team
    return insert success
return inser success


@enduml